# Generated by Django 2.2.2 on 2019-10-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_theory', models.CharField(max_length=120)),
                ('text_theory', models.TextField()),
                ('date_theory', models.DateField()),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stady_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spl', models.CharField(max_length=120)),
                ('name_facult_spl', models.CharField(max_length=120)),
                ('name_way_spl', models.CharField(max_length=120)),
                ('date_start_stady', models.DateField()),
                ('date_finish_stady', models.DateField()),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_skill', models.CharField(max_length=120)),
                ('text_skill', models.TextField()),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_quest', models.CharField(max_length=120)),
                ('text_quest', models.TextField()),
                ('text_response_quest', models.TextField()),
                ('date_quest', models.DateField()),
                ('img_quest', models.CharField(max_length=120)),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=120)),
                ('text_news', models.TextField()),
                ('date_news', models.DateField()),
                ('img_news', models.CharField(max_length=120)),
                ('ID_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
