# Generated by Django 2.2.2 on 2019-10-04 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_list', '0002_user_p'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stady_place',
            new_name='Study_place',
        ),
    ]
