# Generated by Django 2.2.2 on 2019-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0003_auto_20191004_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_1_news',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
