# Generated by Django 2.2.2 on 2019-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_list', '0005_kims'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img_1_news',
        ),
        migrations.AddField(
            model_name='user_p',
            name='image_adress',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
